In [8]:
import numpy as np

a=np.array([1,2,3])

print(a[0])
print(a[1])

(3,)
1
2


In [9]:
b = np.array(
    [[1,2,3], [4,5,6]]
)

# 2행 3열
print(b.shape)

print(b[0])
print(b[1])

print(b[0, 1])
print(b[1, 1])

c = [[1,2,3], [4,5,6]]
print(c[0][1]) 


(2, 3)
[1 2 3]
[4 5 6]
2
5
2


In [20]:
import numpy as np

a = np.array([
    [1,2,5],
    [3,4,6]
])

b = np.array([
    [10, 11,14],
    [12, 13,15]
])

#a배열에 대하여 2보다 큰 값만 출력한다.
print(a[ a > 1 ])

#b배열에 대하여 행(row)끼리,열(column)끼리 연산가능
print(np.sum(b, axis=0)) # 열의 합 (10+12),(11+13),(14+19)
print(np.sum(b, axis=1)) # 행의 합 (10+11+14),(12+13+15)

#두 2차원 배열에 대한 합/차/곱/나눗셈 가능
print(np.add(a, b))      #print(a + b)와 같음
print(np.subtract(a, b)) #print(a - b)와 같음
print(np.multiply(a, b)) #print(a * b)와 같음
print(np.multiply(a, b)) #print(a / b)와 같음


[2 5 3 4 6]
[22 24 29]
[35 40]
[[11 13 19]
 [15 17 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[10 22 70]
 [36 52 90]]
[[10 22 70]
 [36 52 90]]
